### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/discord-embed-bot#1]
## TODO

- [ ] `npm init`
- [ ] TypeScript
    - [ ] Install `typescript` and `@types/node` pkgs
    - [ ] Setup `tsconfig.json`
    - [ ] Add compile solution
        - Automatic (on file change)
        - Display error msgs
- [ ] Prettier
  - [ ] Install `prettier`
  - [ ] `.prettierrc`
  - [ ] `.prettierignore`
- [ ] Add `prod`, `start` and other scripts (`package.json`)
