### ISSUE TITLE
Prep for open source

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/discord-embed-bot#2]
## TODO

- [X] Set GitHub settings (General + Dependabot + [Protect the `main` branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches))
- [X] Set up Issue names and types
- [ ] [Add PR / Issue templates (`.yaml` instead of `.md`?)](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#issue-templates)
- [ ] Move TODO list from to the Issues page
- [ ] [Add GitHub community files?](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types)
    - SECURITY -> turn on the `Private vulnerability reporting` option?
    - CONTRIBUTING
    - CODE_OF_CONDUCT
- [ ] [Write / finish up `README.md`](https://github.com/tox-dev/pipdeptree)
    - [ ] Add motivation / backstory
    - [ ] Add TOC (Table of Contents)
    - [ ] [Write about requirements / setup](https://github.com/tiangolo/fastapi#requirements)
    - [ ] Add instructions / a showcase
        - [A GIF](https://asciinema.org/)
        - A video
        - A written one
- [ ] Add repo + language standards and enforce them (linting, formatting, git commit msgs, pr titles etc)
    - [ ] [**GitHub Actions**](https://github.com/features/actions)
    - [ ] [**pre-commit**](https://pre-commit.com/) / [**pre-commit.ci**](https://pre-commit.ci)

- [ ] Implement CI / CD pipelines
